version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn stylelint "lib/sage-frontend/**/*.{css,scss}" --max-warnings 0
          name: Lint styles inside 'lib/sage-frontend/..'
workflows:
  sage_system_specs:
    jobs:
      - lint
