jobs:
  lint:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn stylelint "lib/sage-frontend/**/*.{css,scss}" --max-warnings 0
          name: Lint styles inside 'lib/sage-frontend/..'
orbs:
  node: circleci/node@3.0.1
version: 2.1
workflows:
  test_my_app:
    jobs:
      - lint