version: 2.1
orbs:
  node: circleci/node@3.0.1
  ruby: circleci/ruby@1.1.1
jobs:
  fronted-lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn stylelint "lib/sage-frontend/**/*.{css,scss}" --max-warnings 0
          name: Lint styles inside 'lib/sage-frontend/..'
  rails-test:
    executor: default
    steps:
      - checkout
      - configure_bundler
      - run:
          name: Install bundle
          command: bundle install
      - run:
          name: RSpec
          command: |
            bundle exec rspec --profile 10 \
                              --format progress
      - store_artifacts:
          path: coverage
      - save_cache:
          key: hix-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
workflows:
  sage_system_specs:
    jobs:
      - frontend-lint
      - rails-test
